import Image from "next/image";
import Link from "next/link";
import React from "react";
import Banner from "../components/Banner";
import DetailsAccordion from "./components/DetailsAccordion";
import "./styles.css";

export const metadata = {
  title: "Pro-Vía Academy Football Gap Year Program",
  description: "Generated by create next app",
};

export default function page() {
  return (
    <main className="relative w-screen overflow-x-hidden">
      {/*Hero Section */}
      <section className="relative h-screen w-screen px-4 lg:px-24 flex lg:items-center lg:pt-0 pt-24 overflow-y-hidden">
        <Image
          src={"/images/AlexMadridBlack.png"}
          className="w-full h-full hidden lg:block "
          fill
          alt="Gap year program background hidden"
        />
        <Image
          src={"/images/AlexMadridBlackMobile.png"}
          className="w-full h-full lg:hidden object-cover"
          fill
          alt="Gap year program background "
        />
        <div className="w-full absolute bottom-0 left-0 h-full bg-gradient-to-t from-black to-transparent to-10%" />
        <div className="relative text-white w-full gap-4">
          <p className="font-ethn  lg:text-2xl font-thin">DREAM DARE DEFY</p>
          <h1 className="lg:text-5xl text-2xl font-ethn lg:w-4/6">
            Your Gap-Year Journey Starts Here
          </h1>
          <p className="lg:w-3/5 mt-2 lg:mt-4 lg:text-lg text-sm">
            Join Pro-Viá Academy&apos;s elite ten-month residency in Madrid,
            where ambition meets opportunity. Train with world-class coaches,
            compete in top Spanish leagues, and enrich your academics with
            NCAA-accredited courses. Immerse yourself in football culture,
            elevate your skills, and prepare for a future in collegiate or
            professional soccer.
          </p>
          <div className="flex gap-4 mt-2 lg:mt-4">
            <Link
              href={"#about"}
              className="py-3 px-3 lg:px-8 font-ethn border-2 border-white font-thin  lg:text-xl"
            >
              Learn More
            </Link>
            <Link
              href={"#about"}
              className="py-3 px-3 lg:px-8 font-ethn bg-white font-light text-black lg:text-xl hover:scale-105 transition-all duration-300"
            >
              Apply Now
            </Link>
          </div>
        </div>
      </section>
      {/*About Section */}
      <section className="lg:h-screen w-screen relative lg:py-0 py-10 flex lg:items-center justify-center ">
        <Image
          src={"/images/Background2.png"}
          className="w-full h-full hidden lg:block"
          fill
          alt="Gap year program background hidden"
        />
        <Image
          src={"/images/Maskgroup.png"}
          className=" lg:hidden object-contain"
          width={250}
          height={150}
          alt="Gap year program background "
        />
        <div className="relative text-white lg:ml-[45vw] mb-24">
          <h2 className="lg:text-5xl text-2xl font-ethn ">
            What is the Pro-Viá Academy Gap-Year Program?
          </h2>
          <p className="mr-10 mt-2 lg:mt-4 lg:text-2xl text-sm font-light">
            Our flagship 10-month residency program in Madrid, Spain, is
            designed for aspiring footballers ready to elevate their game.
            Players train and compete with established Spanish clubs, earn
            academic credits, and experience rich cultural immersion—all while
            living in the heart of European football.
          </p>
        </div>
      </section>
      <Banner
        images={[
          "/images/clubs/leganes.png",
          "/images/clubs/RM.png",
          "/images/clubs/sslr.png",
        ]}
      />
      <DetailsAccordion />
      <section className="w-screen px-24 py-24 flex flex-col items-center bg-black text-white">
        <h2 className="text-4xl font-ethn text-center mb-16">
          The Application Process
        </h2>
        <div className="flex justify-between w-full h-[50vh] gap-10 relative">
          <div className="bg-[#565656] flex flex-col items-center justify-around flex-1 h-full relative card text-center px-4 pb-24 pt-10">
            <span className="font-ethn text-8xl ">1</span>
            <p className="font-bold"></p>
            <p className="text-sm">
              <span className="text-lg font-semibold">Application</span>
              <br />
              Submit your application and supporting documents. Our team will
              review your application and notify you of the outcome.
            </p>
          </div>
          <div className="bg-[#565656] flex flex-col items-center justify-around flex-1 h-full relative card text-center px-4 pb-24 pt-10">
            {" "}
            <span className="font-ethn text-8xl ">2</span>
            <p className="font-bold"></p>
            <p className="text-sm">
              <span className="text-lg font-semibold">Application</span>
              <br />
              Submit your application and supporting documents. Our team will
              review your application and notify you of the outcome.
            </p>
          </div>
          <div className="bg-[#565656] flex flex-col items-center justify-around flex-1 h-full relative card text-center px-4 pb-24 pt-10">
            {" "}
            <span className="font-ethn text-8xl ">3</span>
            <p className="font-bold"></p>
            <p className="text-sm">
              <span className="text-lg font-semibold">Application</span>
              <br />
              Submit your application and supporting documents. Our team will
              review your application and notify you of the outcome.
            </p>
          </div>
          <div className="bg-[#565656] flex flex-col items-center justify-around flex-1 h-full relative card text-center px-4 pb-24 pt-10">
            {" "}
            <span className="font-ethn text-8xl ">4</span>
            <p className="font-bold"></p>
            <p className="text-sm">
              <span className="text-lg font-semibold">Application</span>
              <br />
              Submit your application and supporting documents. Our team will
              review your application and notify you of the outcome.
            </p>
          </div>
          <div className="bg-[#565656] flex flex-col items-center justify-around flex-1 h-full relative card text-center px-4 pb-24 pt-10">
            {" "}
            <span className="font-ethn text-8xl ">5</span>
            <p className="font-bold"></p>
            <p className="text-sm">
              <span className="text-lg font-semibold">Application</span>
              <br />
              Submit your application and supporting documents. Our team will
              review your application and notify you of the outcome.
            </p>
          </div>
          <div className="absolute bottom-0 left-0 w-full h-full bg-gradient-to-t from-black to-transparent to-25%" />
        </div>
        <Link href={"/gap-year/apply"} className="mt-10">
          <button className="bg-white text-black px-8 py-4 font-ethn text-2xl mt-10">
            Apply Now
          </button>
        </Link>
      </section>
    </main>
  );
}
