import Image from "next/image";
import Link from "next/link";
import React from "react";
import Banner from "../components/Banner";
import DetailsAccordion from "./components/DetailsAccordion";
import "./styles.css";
import { StickyScroll } from "@/components/ui/sticky-scroll-reveal";
import PinScroller from "./components/PinScroller";

export const metadata = {
  title: "Pro-Vía Academy Football Gap Year Program",
  description: "Generated by create next app",
};

const content = [
  {
    title: "Authentic Spanish Football",
    description:
      "Experience football at its highest level by training and competing with established Spanish clubs in official league matches. Our players are fully immersed in the fast-paced, technical, and tactical style of Spanish football, gaining real match experience that prepares them for the demands of U.S. college soccer.",
    content: (
      <Image
        fill
        src={"/images/trescantos-club-futbol-base-01-1719e788.webp"}
        className="object-contain"
        alt="authentic spanish football"
      />
    ),
  },
  {
    title: "Specialized Training",
    description:
      "Train like a pro with UEFA-certified coaches who tailor sessions to refine technical skills, tactical awareness, and physical conditioning. With a focus on speed of play, positional intelligence, and adaptability, our program ensures players develop the attributes college coaches seek.",
    content: (
      <Image
        fill
        src={"/images/IMG_5122.JPG"}
        className="object-contain"
        alt="specialized training"
      />
    ),
  },
  {
    title: "Player Profile and Development",
    description:
      "Every athlete undergoes continuous assessment and performance tracking to highlight strengths and areas for improvement. Our Sporting Directors work closely with players to build standout profiles for U.S. college recruitment, providing video analysis, scouting reports, and personalized guidance.",
    content: (
      <Image
        fill
        src={"/images/player-profile-development.png"}
        className="object-contain"
        alt="player profile and development"
      />
    ),
  },
  {
    title: "Holistic Wellness Approach",
    description:
      "Success on the field starts with well-being off the field. Our program provides access to expert physiotherapists, mental performance coaches, sports nutritionists, and strength specialists, ensuring players maintain peak physical and mental condition throughout their journey.",
    content: (
      <Image
        fill
        src={"/images/holistic-wellness.png"}
        className="object-contain"
        alt="holistic wellness approach"
      />
    ),
  },
  {
    title: "Quality Education",
    description:
      "Stay academically on track while pursuing your football ambitions. Players complete a university-level Spanish language course worth 18 ECTS credits, gaining an academic advantage and cultural fluency that sets them apart in both soccer and education.",
    content: (
      <Image
        fill
        src={"/images/quality-education.png"}
        className="object-contain"
        alt="quality education"
      />
    ),
  },
  {
    title: "Top University/Club Connections",
    description:
      "Leverage our deep-rooted network in both the U.S. college system and professional football. With strong ties to D1 programs, scouts, and European clubs, we create pathways for players to advance their careers at the collegiate or professional level.",
    content: (
      <Image
        fill
        src={"/images/university-club-connections.png"}
        className="object-contain"
        alt="top university and club connections"
      />
    ),
  },
];

export default function page() {
  return (
    <main className="relative w-screen overflow-x-clip">
      {/*Hero Section */}
      <section className="relative h-screen w-screen px-4 lg:px-24 flex lg:items-center lg:pt-0 pt-24 overflow-y-hidden ">
        <Image
          src={"/images/AlexMadridBlack.png"}
          className="w-full h-full hidden lg:block object-cover "
          fill
          alt="Gap year program background hidden "
        />
        <Image
          src={"/images/AlexMadridBlackMobile.png"}
          className="w-full h-full lg:hidden object-cover"
          fill
          alt="Gap year program background "
        />
        <div className="w-full absolute bottom-0 left-0 h-full bg-gradient-to-t from-black to-transparent to-10%" />
        <div className="relative text-white w-full gap-4">
          <p className="font-ethn  lg:text-2xl font-thin">DREAM DARE DEFY</p>
          <h1 className="lg:text-5xl text-2xl font-ethn lg:w-4/6">
            Your Gap-Year Journey Starts Here
          </h1>
          <p className="lg:w-3/5 mt-2 lg:mt-4 lg:text-lg text-sm hidden lg:block">
            Join Pro-Viá Academy&apos;s elite ten-month residency in Madrid,
            where ambition meets opportunity. Train with world-class coaches,
            compete in top Spanish leagues, and enrich your academics with
            NCAA-accredited courses. Immerse yourself in football culture,
            elevate your skills, and prepare for a future in collegiate or
            professional soccer.
          </p>
          <p className="lg:w-3/5 mt-2 lg:mt-4 lg:text-lg text-sm lg:hidden">
            Join Pro-Viá Academy&apos;s elite ten-month residency in Madrid,
            where ambition meets opportunity. Train with world-class coaches,
            compete in top Spanish leagues, and enrich your academics with
            NCAA-accredited courses.
          </p>
          <div className="flex gap-4 mt-2 lg:mt-4">
            <Link
              href={"#about"}
              className="py-3 px-3 lg:px-8 font-ethn border-2 border-white font-thin  lg:text-xl"
            >
              Learn More
            </Link>
            <Link
              href={"#about"}
              className="py-3 px-3 lg:px-8 font-ethn bg-white font-light text-black lg:text-xl hover:scale-105 transition-all duration-300"
            >
              Apply Now
            </Link>
          </div>
        </div>
      </section>
      {/*About Section */}
      <section className="lg:h-screen w-screen relative lg:py-0 py-10 flex items-center justify-center flex-col-reverse lg:flex-row px-4 lg:px-0">
        <Image
          src={"/images/Background2.png"}
          className="w-full h-full hidden lg:block"
          fill
          alt="Gap year program background hidden"
        />
        <Image
          src={"/images/Maskgroup.png"}
          className=" lg:hidden object-contain "
          width={250}
          height={150}
          alt="Gap year program background "
        />
        <div className="relative text-white lg:ml-[45vw] lg:mb-24 mb-8 text-center lg:text-left">
          <h2 className="lg:text-5xl text-xl font-ethn ">
            What is the Pro-Viá Academy Gap-Year Program?
          </h2>
          <p className="lg:mr-10 mt-2 lg:mt-4 lg:text-2xl text-md font-light">
            Our flagship 10-month residency program in Madrid, Spain, is
            designed for aspiring footballers ready to elevate their game.
            Players train and compete with established Spanish clubs, earn
            academic credits, and experience rich cultural immersion—all while
            living in the heart of European football.
          </p>
        </div>
      </section>
      <Banner
        images={[
          "/images/clubs/leganes.png",
          "/images/clubs/RM.png",
          "/images/clubs/sslr.png",
        ]}
      />
      {/* <h2 className="font-ethn lg:text-5xl text-xl text-white px-4 lg:px-24 mt-24 mb-5">
        Why Choose Pro-Vía Academy&apos;s Gap-Year Program
      </h2> */}
      {/* <section className="w-screen hidden lg:block">
        <StickyScroll content={content} />{" "}
      </section> */}
      <PinScroller content={content} />
      {/* <DetailsAccordion /> */}
      <section className="w-screen lg:px-24 px-4 py-4 lg:py-24 flex flex-col items-center bg-black text-white">
        <h2 className="lg:text-4xl text-2xl font-ethn lg:text-center lg:mb-16 mb-8">
          The Application Process
        </h2>
        <div className="flex flex-col lg:flex-row lg:justify-between w-full lg:h-[50vh] gap-10 relative">
          <div className="bg-[#565656] flex flex-col justify-start flex-1 h-full relative card lg:text-center px-4 pb-4 pt-4 lg:pb-24 lg:pt-10 lg:shadow-none shadow-md shadow-white">
            <span className="font-ethn lg:text-8xl  text-5xl mb-10 mt-5">
              1
            </span>

            <p className="text-sm">
              <span className="text-lg font-semibold">Application</span>
              <br />
              Submit your application and supporting documents. Our team will
              review your application and notify you of the outcome.
            </p>
          </div>
          <div className="bg-[#565656] flex flex-col  justify-start flex-1 h-full relative card lg:text-center px-4 pb-4 pt-4 lg:pb-24 lg:pt-10 lg:shadow-none shadow-md shadow-white">
            {" "}
            <span className="mb-10 mt-5 font-ethn lg:text-8xl text-5xl ">
              2
            </span>
            <p className="text-sm">
              <span className="text-lg font-semibold">Enrollment</span>
              <br />
              Receive your acceptance letter and start the visa process
            </p>
          </div>
          <div className="bg-[#565656] flex flex-col  justify-start flex-1 h-full relative card lg:text-center px-4 pb-4 pt-4 lg:pb-24 lg:pt-10 lg:shadow-none shadow-md shadow-white">
            {" "}
            <span className="mb-10 mt-5 font-ethn lg:text-8xl text-5xl ">
              3
            </span>
            <p className="text-sm">
              <span className="text-lg font-semibold">Arrival</span>
              <br />
              Arrive in Madrid on Aug 10th where we will pick you up and help
              you get adjusted
            </p>
          </div>
          <div className="bg-[#565656] flex flex-col  justify-start flex-1 h-full relative card lg:text-center px-4 pb-4 pt-4 lg:pb-24 lg:pt-10 lg:shadow-none shadow-md shadow-white">
            {" "}
            <span className="mb-10 mt-5 font-ethn lg:text-8xl text-5xl ">
              4
            </span>
            <p className="text-sm">
              <span className="text-lg font-semibold">Development</span>
              <br />
              Our sport directors will be creating development plans for each
              player and monitor their development
            </p>
          </div>
          <div className="bg-[#565656] flex flex-col  justify-start flex-1 h-full relative card lg:text-center px-4 pb-4 pt-4 lg:pb-24 lg:pt-10 lg:shadow-none shadow-md shadow-white">
            {" "}
            <span className="mb-10 mt-5 font-ethn lg:text-8xl text-5xl ">
              5
            </span>
            <p className="text-sm">
              <span className="text-lg font-semibold">Commitment</span>
              <br />
              Our Sport directors in the USA will market your player profile and
              help you get commitments at top Universities or pro teams.
            </p>
          </div>
          <div className="absolute bottom-0 left-0 w-full h-full bg-gradient-to-t from-black to-transparent to-25% hidden lg:block" />
        </div>
        <Link href={"/gap-year/apply"} className="mt-10 lg:mb-0 mb-10">
          <button className="bg-white text-black px-8 py-4 font-ethn text-2xl mt-10">
            Apply Now
          </button>
        </Link>
      </section>
    </main>
  );
}
