import "./globals.css";
import Footer from "./components/Footer";
import localFont from "next/font/local";

const Clash = localFont({ src: "./ClashGrotesk-Variable.woff2" });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://use.typekit.net/aha6akh.css" />
      </head>
      <body className={`${Clash.className}  antialiased`}>
        {children}
        <Footer />
      </body>
    </html>
  );
}
