import "./globals.css";
import Footer from "./components/Footer";
import localFont from "next/font/local";
import Nav from "./components/Nav";
import ComingSoon from "./ComingSoon";
import { Toaster } from "react-hot-toast";

const Clash = localFont({ src: "./ClashGrotesk-Variable.woff2" });

export const metadata = {
  title: "Pro-Vía Academy: The Best Football Programs in Spain",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://use.typekit.net/aha6akh.css" />
      </head>
      <body className={`${Clash.className}  antialiased bg-black`}>
        {/* <Nav /> */}
        {/* {children} */}
        {/* <Footer /> */}
        <ComingSoon />
        <Toaster
          toastOptions={{
            // Define default options
            className: "",
            duration: 5000,
            removeDelay: 1000,
            style: {
              background: "#FFFFF",
              borderRadius: "0px",
              padding: "16px",
            },
          }}
        />
      </body>
    </html>
  );
}
